<a href="https://colab.research.google.com/github/Ahdysya/data_science_w1/blob/main/Tutorial03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name= Ratu Ahdys Khairany

Matric Number= 24225208

In [7]:
import numpy as np

1. Create a numpy array on size 2 x 2

In [8]:
arr_2x2 = np.array([[1,2],[3,4]])

print("2x2 Array:\n", arr_2x2)

2x2 Array:
 [[1 2]
 [3 4]]


2. Create a random numpy array of size 3 x 4

In [9]:
random_arr_3x4 = np.random.rand(3,4)

print("3x4 Random Array:\n", random_arr_3x4)


3x4 Random Array:
 [[0.86786778 0.28056692 0.07774264 0.3684487 ]
 [0.03681415 0.00266763 0.28092797 0.81769086]
 [0.56679488 0.76462529 0.13273254 0.13275478]]


3. Create a numpy array of ones and a numpy array of zeroses

In [10]:
ones_array = np.ones((2, 3))
zeros_array = np.zeros((2, 3))

print("Ones Array:\n", ones_array)
print("\nZeros Array:\n", zeros_array)


Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]


4. Create a random numpy array of size 6x3 and transpose it

In [11]:
random_arr_6x3 = np.random.rand(6, 3)
transposed_arr = np.transpose(random_arr_6x3)

print("6x3 Random Array:\n", random_arr_6x3)
print("\nTransposed Array:\n", transposed_arr)

6x3 Random Array:
 [[0.0919383  0.53656108 0.66250715]
 [0.58699852 0.70230369 0.26102633]
 [0.6132349  0.99397023 0.59956368]
 [0.7037242  0.73084215 0.55699542]
 [0.85074789 0.58196452 0.87081834]
 [0.26031964 0.68117202 0.91016261]]

Transposed Array:
 [[0.0919383  0.58699852 0.6132349  0.7037242  0.85074789 0.26031964]
 [0.53656108 0.70230369 0.99397023 0.73084215 0.58196452 0.68117202]
 [0.66250715 0.26102633 0.59956368 0.55699542 0.87081834 0.91016261]]


5. Create two random numpy array of size n x p and p x m and then compute the dot product

In [12]:
import numpy as np


n = 2
p = 3
m = 4

array_np = np.random.rand(n, p)
array_pm = np.random.rand(p, m)

dot_product = np.dot(array_np, array_pm)

print("Array np (n x p):\n", array_np)
print("\nArray pm (p x m):\n", array_pm)
print("\nDot Product Result (n x m):\n", dot_product)


Array np (n x p):
 [[0.02568791 0.79821812 0.51882301]
 [0.82663848 0.9206171  0.51863207]]

Array pm (p x m):
 [[0.80591262 0.42203689 0.04121544 0.99387122]
 [0.64381611 0.46412234 0.96678266 0.00172305]
 [0.27461541 0.5671308  0.84081224 0.12440162]]

Dot Product Result (n x m):
 [[0.67708469 0.67555261 1.20899491 0.09144826]
 [1.40133086 1.07028311 1.36017911 0.88767713]]
