<a href="https://colab.research.google.com/github/Ahdysya/data_science_w1/blob/main/Tutorial03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np

1. Create a numpy array on size 2 x 2

In [12]:
arr_2x2 = np.array([[1,2],[3,4]])

print("2x2 Array:\n", arr_2x2)

2x2 Array:
 [[1 2]
 [3 4]]


2. Create a random numpy array of size 3 x 4

In [13]:
random_arr_3x4 = np.random.rand(3,4)

print("3x4 Random Array:\n", random_arr_3x4)


3x4 Random Array:
 [[0.48673958 0.38166005 0.950011   0.77959813]
 [0.31623175 0.83723013 0.92326783 0.25625327]
 [0.65261745 0.84995791 0.76417568 0.95360328]]


3. Create a numpy array of ones and a numpy array of zeroses

In [14]:
ones_array = np.ones((2, 3))
zeros_array = np.zeros((2, 3))

print("Ones Array:\n", ones_array)
print("\nZeros Array:\n", zeros_array)


Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]


4. Create a random numpy array of size 6x3 and transpose it

In [15]:
random_arr_6x3 = np.random.rand(6, 3)
transposed_arr = np.transpose(random_arr_6x3)

print("6x3 Random Array:\n", random_arr_6x3)
print("\nTransposed Array:\n", transposed_arr)

6x3 Random Array:
 [[0.90922067 0.07986979 0.43751938]
 [0.51349787 0.84510003 0.75345985]
 [0.63000738 0.99075349 0.70624982]
 [0.18860121 0.93391037 0.85497356]
 [0.0889122  0.94563114 0.56383202]
 [0.66375137 0.10809839 0.27206001]]

Transposed Array:
 [[0.90922067 0.51349787 0.63000738 0.18860121 0.0889122  0.66375137]
 [0.07986979 0.84510003 0.99075349 0.93391037 0.94563114 0.10809839]
 [0.43751938 0.75345985 0.70624982 0.85497356 0.56383202 0.27206001]]


5. Create two random numpy array of size n x p and p x m and then compute the dot product

In [16]:
n = 2
p = 3
m = 4

array_np = np.random.rand(n, p)
array_pm = np.random.rand(p, m)

dot_product = np.dot(array_np, array_pm)

print("Array np (n x p), array_np")
print("\nArray pm (p x m), array_pm")
print("\nDot Product Result (n x m):\n, dot_product")


Array np (n x p), array_np

Array pm (p x m), array_pm

Dot Product Result (n x m):
, dot_product
