<a href="https://colab.research.google.com/github/Ahdysya/data_science_w1/blob/main/Tutorial03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np

1. Create a numpy array on size 2 x 2

In [21]:
arr_2x2 = np.array([[1,2],[3,4]])

print("2x2 Array:\n", arr_2x2)

2x2 Array:
 [[1 2]
 [3 4]]


2. Create a random numpy array of size 3 x 4

In [22]:
random_arr_3x4 = np.random.rand(3,4)

print("3x4 Random Array:\n", random_arr_3x4)


3x4 Random Array:
 [[0.00792546 0.15069283 0.51313578 0.80807248]
 [0.10094426 0.34270446 0.34538102 0.71675985]
 [0.19255723 0.89361131 0.19989876 0.72732953]]


3. Create a numpy array of ones and a numpy array of zeroses

In [23]:
ones_array = np.ones((2, 3))
zeros_array = np.zeros((2, 3))

print("Ones Array:\n", ones_array)
print("\nZeros Array:\n", zeros_array)


Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]


4. Create a random numpy array of size 6x3 and transpose it

In [24]:
random_arr_6x3 = np.random.rand(6, 3)
transposed_arr = np.transpose(random_arr_6x3)

print("6x3 Random Array:\n", random_arr_6x3)
print("\nTransposed Array:\n", transposed_arr)

6x3 Random Array:
 [[0.84555778 0.86092575 0.99677536]
 [0.50531482 0.36186561 0.43884536]
 [0.98600867 0.27553556 0.19547307]
 [0.79086233 0.06466447 0.60177693]
 [0.87225019 0.13518854 0.05966031]
 [0.02349925 0.99872524 0.12469243]]

Transposed Array:
 [[0.84555778 0.50531482 0.98600867 0.79086233 0.87225019 0.02349925]
 [0.86092575 0.36186561 0.27553556 0.06466447 0.13518854 0.99872524]
 [0.99677536 0.43884536 0.19547307 0.60177693 0.05966031 0.12469243]]


5. Create two random numpy array of size n x p and p x m and then compute the dot product

In [25]:
n = 2
p = 3
m = 4

array_np = np.random.rand(n, p)
array_pm = np.random.rand(p, m)

dot_product = np.dot(array_np, array_pm)

print("Array np (n x p):\n", array_np)
print("\nArray pm (p x m):\n", array_pm)
print("\nDot Product Result (n x m):\n, dot_product")


Array np (n x p):
 [[0.62176689 0.48303998 0.65628034]
 [0.98185029 0.22953201 0.67436468]]

Array pm (p x m):
 [[0.9019335  0.32484563 0.83446952 0.17803897]
 [0.58483089 0.37785972 0.32100572 0.48427277]
 [0.52051272 0.85901907 0.98956038 0.86147162]]

Dot Product Result (n x m):
, dot_product
